name: Build & Push both services to ACR (monorepo)

on:
  push:
    branches: [ "main" ]
    paths:
      - "catalogo/**"
      - "paciente/**"
      - ".github/workflows/deploy.yml"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - service: catalogo
            context: ./catalogo
            image: catalogo-service
          - service: paciente
            context: ./paciente
            image: paciente-service
    steps:
      - name: üì• Checkout
        uses: actions/checkout@v4

      - name: üîë Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: üè∑Ô∏è Set version tag (short sha)
        id: vars
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: üèóÔ∏è Build & Push ${{ matrix.service }}
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/${{ matrix.image }}:latest ${{ matrix.context }}
          docker tag  ${{ secrets.ACR_LOGIN_SERVER }}/${{ matrix.image }}:latest ${{ secrets.ACR_LOGIN_SERVER }}/${{ matrix.image }}:${{ steps.vars.outputs.TAG }}
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/${{ matrix.image }}:latest
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/${{ matrix.image }}:${{ steps.vars.outputs.TAG }}